In [1]:
import numpy as np

### Задача №1

In [14]:
A = np.matrix([[1, 2, 1],
              [-2, 1, 1]])

B = np.matrix([[3, 1],
              [-1, 0],
              [2, 4]])

C = np.matrix([[-2, 2],
              [1, -1],
              [1, 2]])

result = A + 2 * B.transpose()
result_2 = B + 2 * C

print("Ответ первой задачи: \n", result,"\n \n", result_2)

Ответ первой задачи: 
 [[7 0 5]
 [0 1 9]] 
 
 [[-1  5]
 [ 1 -2]
 [ 4  8]]


### Задача №2

In [17]:
x = np.zeros((8,8),dtype='int32')
x[1::2,::2] = 1
x[::2,1::2] = 1

print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Задача №3

In [24]:
vector_1 = np.arange(0,1.5,0.1)

vector_2 = np.arange(0,6, dtype='int')

print(f'количество элементов = {len(vector_1)}')
print(vector_1)

print(f'количество элементов = {len(vector_2)}')
print(vector_2)

количество элементов = 15
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
количество элементов = 6
[0 1 2 3 4 5]


In [25]:
matrix1 = vector_1.reshape(5,3)

matrix2 = vector_2.reshape((3,2))

print("Матрица 5х3 вектора1:  \n",
    matrix1)
print("Матрица 3х2 вектора2:  \n",
    matrix2)
print("Произведение матриц:  \n",
np.dot(matrix1, matrix2))

Матрица 5х3 вектора1:  
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
Матрица 3х2 вектора2:  
 [[0 1]
 [2 3]
 [4 5]]
Произведение матриц:  
 [[ 1.   1.3]
 [ 2.8  4. ]
 [ 4.6  6.7]
 [ 6.4  9.4]
 [ 8.2 12.1]]


### Задача №4

In [30]:
vector_3 = np.arange(1,72,2)

print(f"Вектор из {len(vector_3)} элементов :  \n",
    *vector_3)

Вектор из 36 элементов :  
 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71


In [36]:
result_list = []
for i in vector_3:
    if i % 3 == 0:
        result_list.append(i)
print("Исходный вектор :  \n", *vector_3)
print("Элементы со значениями кратными 3 :  \n", *result_list)

Исходный вектор :  
 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71
Элементы со значениями кратными 3 :  
 3 9 15 21 27 33 39 45 51 57 63 69
